### ISSUE TITLE
Create CLI commands for joints info

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/flick#11]
These commands include:

- `show-joints --location x  --rating n --veg`
- `joint-info id --reviews`
- `show-menu id --veg`

**Comment by akshgpt7** [comment]
I'm working on this.

**Comment by bepotts** [comment]
Hey @akshgpt7 , which command are you working on? I can do one.

**Comment by akshgpt7** [comment]
I completed show-joints.
You can pull it from my PR.
